name: Heroku

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kk6gpv-api"
          heroku_email: "areed145@gmail.com"
          buildpack: "https://github.com/heroku/heroku-buildpack-python.git"
